### ISSUE TITLE
zom on fdroid

### ISSUE THREAD

**Issue by pravi** [ChatSecure/Zom-iOS#3]
I could not find zom for android, so posting it here.

Please provide zom via fdroid. I can't find it in Guardian project's fdroid repo.

**Comment by davidchiles** [comment]
This is the iOS repo you probably want to open an issue on the Android repo.

**Comment by pravi** [comment]
Yes, this is iOS repo. But android repo is nether listed on zom website or in chatsecure github group.

**Comment by davidchiles** [comment]
@pravi https://github.com/zom
